name: Create release and upload solution to Azure blob storage CI

on:
  push:
    branches: release

jobs:
  main:
    uses: BeverCRM/Workflow-Build-Release-Upload-CI/.github/workflows/build-release-upload-ci.yml@master
    secrets: inherit
    with:
      control-title: Schedule Board View
      control-description: This control converts any dataset that has start date and end date in its records into Schedule Board.
      control-thumbnail-url: https://user-images.githubusercontent.com/61091700/222457753-d6a2816d-99e0-4fe1-937b-be2d393c5977.png
      control-primary-image-url: https://user-images.githubusercontent.com/61091700/222457753-d6a2816d-99e0-4fe1-937b-be2d393c5977.png
      control-youtube-video-url: https://www.youtube.com/watch?v=PD5IvVbYWBs
      control-tags: Dataset, Grid, Board
      create-new-release: false
